/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions/$questionId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions': typeof QuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  AuthLoginRoute: AuthLoginRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
