/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityThreadIdRouteImport } from './routes/community/$threadId'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions/$questionId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as QuestionsQuestionIdResultSubmissionIdRouteImport } from './routes/questions/$questionId_.result.$submissionId'
import { Route as QuestionsQuestionIdInterviewRouteImport } from './routes/questions/$questionId_.interview'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityThreadIdRoute = CommunityThreadIdRouteImport.update({
  id: '/community/$threadId',
  path: '/community/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdResultSubmissionIdRoute =
  QuestionsQuestionIdResultSubmissionIdRouteImport.update({
    id: '/questions/$questionId_/result/$submissionId',
    path: '/questions/$questionId/result/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuestionsQuestionIdInterviewRoute =
  QuestionsQuestionIdInterviewRouteImport.update({
    id: '/questions/$questionId_/interview',
    path: '/questions/$questionId/interview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions/': typeof QuestionsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/questions/$questionId/result/$submissionId': typeof QuestionsQuestionIdResultSubmissionIdRoute
  '/questions/$questionId/interview': typeof QuestionsQuestionIdInterviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions': typeof QuestionsIndexRoute
  '/community': typeof CommunityIndexRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/questions/$questionId/result/$submissionId': typeof QuestionsQuestionIdResultSubmissionIdRoute
  '/questions/$questionId/interview': typeof QuestionsQuestionIdInterviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/questions/': typeof QuestionsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/questions/$questionId_/result/$submissionId': typeof QuestionsQuestionIdResultSubmissionIdRoute
  '/questions/$questionId_/interview': typeof QuestionsQuestionIdInterviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/settings'
    | '/pricing'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions/'
    | '/community/'
    | '/community/$threadId'
    | '/questions/$questionId/result/$submissionId'
    | '/questions/$questionId/interview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/settings'
    | '/pricing'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions'
    | '/community'
    | '/community/$threadId'
    | '/questions/$questionId/result/$submissionId'
    | '/questions/$questionId/interview'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/settings'
    | '/pricing'
    | '/auth/login'
    | '/questions/$questionId'
    | '/submissions/$submissionId'
    | '/questions/'
    | '/community/'
    | '/community/$threadId'
    | '/questions/$questionId_/result/$submissionId'
    | '/questions/$questionId_/interview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  SettingsRoute: typeof SettingsRoute
  PricingRoute: typeof PricingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityThreadIdRoute: typeof CommunityThreadIdRoute
  QuestionsQuestionIdResultSubmissionIdRoute: typeof QuestionsQuestionIdResultSubmissionIdRoute
  QuestionsQuestionIdInterviewRoute: typeof QuestionsQuestionIdInterviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId_/result/$submissionId': {
      id: '/questions/$questionId_/result/$submissionId'
      path: '/questions/$questionId/result/$submissionId'
      fullPath: '/questions/$questionId/result/$submissionId'
      preLoaderRoute: typeof QuestionsQuestionIdResultSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId_/interview': {
      id: '/questions/$questionId_/interview'
      path: '/questions/$questionId/interview'
      fullPath: '/questions/$questionId/interview'
      preLoaderRoute: typeof QuestionsQuestionIdInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$threadId': {
      id: '/community/$threadId'
      path: '/community/$threadId'
      fullPath: '/community/$threadId'
      preLoaderRoute: typeof CommunityThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  SettingsRoute: SettingsRoute,
  PricingRoute: PricingRoute,
  AuthLoginRoute: AuthLoginRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityThreadIdRoute: CommunityThreadIdRoute,
  QuestionsQuestionIdResultSubmissionIdRoute:
    QuestionsQuestionIdResultSubmissionIdRoute,
  QuestionsQuestionIdInterviewRoute: QuestionsQuestionIdInterviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
